//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uranus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HelixToolkit_Wpf {
            get {
                object obj = ResourceManager.GetObject("HelixToolkit_Wpf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PilotFish_UAV {
            get {
                object obj = ResourceManager.GetObject("PilotFish_UAV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PilotFish_UAV_P01 {
            get {
                object obj = ResourceManager.GetObject("PilotFish_UAV_P01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PilotFish_UAV1 {
            get {
                object obj = ResourceManager.GetObject("PilotFish_UAV1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuaternionView {
            get {
                object obj = ResourceManager.GetObject("QuaternionView", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uranus 姿态运动控制模块 上位机
        ///
        ///V1.2.2.1
        ///1. 升级About对话框, 增加升级内容日志记录
        ///2. 添加新版AT指令集的 IMU配置界面，操作更加直观。同时保留旧版IMU配置
        ///3. IMU配置对话框从全屏改为非全屏
        ///
        ///V1.2.3.0
        ///1. 修复了3D DiretX空间错误文件名的问题
        ///2. 测试了软件在Win8和Win10下兼容性的问题
        ///
        ///V1.2.3.1
        ///1. 将所有图标改为 ZedGraph
        ///2. 细微调节美化系统界面
        ///
        ///V1.2.3.2
        ///1. IMU config 窗体关闭时会发送 AT+EOUT=1(开启数据输出)
        ///2. 当子窗体处于非活动状态时，关闭数据显示
        ///3. KBOOT调整，执行复位后发送PING 以让下位机获得当前波特率（适用于 KBOOT ROM）
        ///
        ///V1.2.3.3
        ///1. IMU界面显示增加气压显示 取消ID及KEY显示
        ///
        ///V1.2.3.4
        ///1. 解析包过程 做成单独的线程来执行
        ///2. 增加TeeChat替换原来的ZedGraphic（未开放）
        ///3. 增加新协议(CHLink)包解析支持
        ///4. 更换新logo
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string updatelog {
            get {
                return ResourceManager.GetString("updatelog", resourceCulture);
            }
        }
    }
}
